services:
  auth-service:
    build: ./auth-service
    image: auth-service:latest
    restart: always
    ports:
      - "4001:4001"
    env_file:
      - .env
    environment:
      - PORT=4001
  users-service:
    build: ./users-service
    image: users-service:latest
    restart: always
    ports:
      - "4002:4002"
    env_file:
      - .env
    environment:
      - PORT=4002
  swipes-service:
    build: ./swipes-service
    image: swipes-service:latest
    restart: always
    ports:
      - "4003:4003"
    env_file:
      - .env
    environment:
      - PORT=4003
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - users-service
      - swipes-service

      #ola k asen
