events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        least_conn;
        server auth-service:4001 weight=3;
    }

    upstream users_service {
        least_conn; 
        server users-service:4002;
    }

    upstream swipes_service {
        least_conn;
        server swipes-service:4003;
    }

    # Timemout config
    # proxy_connect_timeout 30s;
    # proxy_send_timeout 30s;
    # proxy_read_timeout 30s;
    # proxy_buffering on;
    # proxy_buffer_size 4k;
    # proxy_buffers 8 4k;

    server {
        listen 80;

        # Health check endpoint
        location /nginx-status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }

        # Users Microservice
        location ~ ^/auth(/.*)?$ {
            proxy_pass http://auth_service$1$is_args$args;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            
            # Configuración de timeouts específicos
            proxy_connect_timeout 15s;
            proxy_send_timeout 15s;
            proxy_read_timeout 15s;
            
            # Error Handling
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
            proxy_next_upstream_timeout 10s;
        }

        location ~ ^/users(/.*)?$ {
            proxy_pass http://users_service$1$is_args$args;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;

             # Error Handling
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
            proxy_next_upstream_timeout 10s;
        }

        location ~ ^/swipes(/.*)?$ {
            proxy_pass http://swipes_service$1$is_args$args;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;

             # Error Handling
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
            proxy_next_upstream_timeout 10s;
        }

        # Global error handling
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}